### ISSUE TITLE
JOSM Matsim Plugin 오류

### ISSUE THREAD

**Issue by Hotlineblinn** [Hotlineblinn/beam#1]
matsim 오류

**Comment by wkstonelee** [comment]
[matsim.zip](https://github.com/Hotlineblinn/beam/files/6007249/matsim.zip)

1. 첨부된 압축파일의 압축을 해제
2. josm 프로그램 종료
3. C:\Users\<사용자명>\AppData\Roaming\JOSM\plugins 디렉토리의 matsim.jar 파일 삭제
4. 압축 해제한 matsim.jar 파일 복사
5. 프로그램 실행

하고 프로그램 실행하면 오류 발생 안되는 것 확인할 수 있습니다.
